# Generated by Django 5.2.2 on 2025-06-10 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('semestre', models.PositiveSmallIntegerField()),
                ('creditos', models.PositiveSmallIntegerField()),
                ('docente_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=15, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('clave_encriptada', models.CharField(max_length=255)),
                ('carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('semestre', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('examen', 'Examen'), ('práctica', 'Práctica'), ('trabajo', 'Trabajo'), ('otro', 'Otro')], max_length=20)),
                ('fecha', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('instrucciones', models.TextField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('apunte', 'Apunte'), ('libro', 'Libro'), ('video', 'Video'), ('link', 'Link')], max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trimestre', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III')], max_length=3)),
                ('año_academico', models.CharField(max_length=9)),
                ('seccion', models.CharField(blank=True, max_length=5, null=True)),
                ('estado', models.CharField(choices=[('inscrita', 'Inscrita'), ('retirada', 'Retirada')], default='inscrita', max_length=10)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evaluation')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='AgentInteraction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('respuesta_generada', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('intencion_detectada', models.CharField(blank=True, max_length=100, null=True)),
                ('confianza', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
