# Generated by Django 5.2.3 on 2025-07-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_synced',
            field=models.BooleanField(default=False, help_text='True si ya ejecutó el scraping de evaluaciones'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_synced',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora de la última sincronización', null=True),
        ),
    ]
