# Generated by Django 5.2.3 on 2026-08-21 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentInteraction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("pregunta", models.TextField()),
                ("respuesta_generada", models.TextField()),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                ("intencion_detectada", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "confianza",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
