# Generated by Django 5.2.3 on 2025-06-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_subject_semestre_remove_user_semestre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='creditos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
