# Generated by Django 5.2.3 on 2025-06-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_subject_creditos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='docente_nombre',
        ),
        migrations.AddField(
            model_name='subject',
            name='profesor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
