"""
Django settings for uba_assistant project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# ———————– PATCH django-q / Django>=4.0 ———————–
from django.core.signing import TimestampSigner as _DjangoTS
import django_q.core_signing

class CompatTimestampSigner(_DjangoTS):
    """
    Extiende el TimestampSigner de Django>=4 
    para aceptar key y salt como args posicionales,
    tal y como django-q espera llamarlo.
    """
    def __init__(self, key=None, salt=None, sep=':', **kwargs):
        super().__init__(key=key, salt=salt, sep=sep, **kwargs)

# Sustituimos el signer interno de django-q por el compatible
django_q.core_signing.TimestampSigner = CompatTimestampSigner
# ——————————————————————————————————————————————

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m=(2afvc!5n&otxksu8i-^@tai0niat57yw@lv66r4^l-ig+q6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Agregamos la configuración para servir archivos media (por ejemplo, las imágenes descargadas)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"


# Application definition

INSTALLED_APPS = [
    # Apps predeterminadas de Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_q',
    
    # Apps de terceros
    'rest_framework',
    'drf_yasg',
    'corsheaders',

    # Mi aplicación
    'core',
]
INSTALLED_APPS += ['rest_framework_simplejwt.token_blacklist']

Q_CLUSTER = {
    'name': 'DjangoQCluster',
    'workers': 5,          # número de procesos worker
    'timeout': 500,         # tiempo máximo (s) por tarea
    'retry': 1000,          # reintentos en caso de fallo (s)
    'queue_limit': 50,     # tamaño máximo de cola
    'bulk': 15,            # cuántas tareas coge cada worker a la vez
    'orm': 'default',      # usa la base de datos de Django como broker
        # <<< desactiva por completo tareas programadas >>>
    'poll': 0,

}

SIMPLE_JWT = {
  'BLACKLIST_AFTER_ROTATION': True,
  # demás ajustes…
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Añadimos aquí
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'uba_assistant.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # añadir rutas a templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'uba_assistant.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'uba_assistant_db',
        'USER': 'root',
        'PASSWORD': '',  # contraseña de XAMPP
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'CONN_MAX_AGE': 60, 
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SWAGGER_SETTINGS = {
    'DEFAULT_AUTO_SCHEMA_CLASS': 'drf_yasg.inspectors.SwaggerAutoSchema',
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ]
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',    # Cambia a 'DEBUG' si quieres ver los logger.debug()
    },
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LOGIN_URL = '/login-page/'
LOGIN_REDIRECT_URL = '/dashboard/'

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True

AUTH_USER_MODEL = 'core.User'